### ISSUE TITLE
how to use the code ?

### ISSUE THREAD

**Issue by georgiazhang** [nassarofficial/Siamese_network_caffe#2]
i have two questions,
1.how to use  the code
2.how to build the two test.txt

**Comment by nassarofficial** [comment]
If you're new to caffe check out the tutorials on how to train, which will be much better than my explanation but however I will try.
1. Just normally as you would use any other caffe model:
./build/tools/caffe train --solver=models/SiameseNetworkCaffe/solver.prototxt

2. check out the readme file for the format of test.txt and test2.txt. It should only contain a list of your path to the file and it's label.

**Comment by georgiazhang** [comment]
Could you give more details about your task ? I really spend lots of time to make it work.

**Comment by nassarofficial** [comment]
Please elaborate more, I am not sure what you mean.

**Comment by georgiazhang** [comment]
I  want to use the siamese network to train my own dataset,the dataset is about 95 persons, each person has 100 picture.I understand the principles of your algorithm, that is ,cut the dataset into two parts, one is train1,another is train2,and you change the prototxt. So my questions here are:

1.how to creat the train.txt and train2.txt,just randomly pick a part of my train dataset ,and copy the path of each picture, and then compare the two txt ,if the image files in the corresponding lines of the two .txt files are of the same person,then the label is 1,otherwise ,the label is 0?

2.Do you have the code to do this work? The computation is huge.

     When you get the train.txt and the test.txt ,you begin to run the new siamese-network.In the original siamese network,i input the commands as follows:
(ignore the path, i want to know which file you used in your work.)
   ./data/mnist/get_mnist.sh    //we us our own dataset 
  ./examples/siamese/create_mnist_siamese.sh  //do you use the same command?
  if not ,can you show me your file? i changed the DATA to my work dir,but there is error about the train-images-idx3-ubyte, do i need to change the file?
./examples/siamese/train_mnist_siamese.sh // we need to change the file, --solver should be your file solver.prototxt.
        Do i understand the work right? I am so confused.Help me!PLZ!

**Comment by georgiazhang** [comment]
can you please help me with the questions?

**Comment by nassarofficial** [comment]
1. Yes exactly, and randomize the training and testing set.
2. What do you mean by the code to do this work, and that it is huge? Btw this is not my algorithm, Im just implementing it using image_raw in a git just cleanly because this doesnt exist anywhere else easily. No do not follow the siamese tutorial in caffe, it has nothing to do with it. It seems you have not experimented much with caffe, so I suggest you try to follow this http://caffe.berkeleyvision.org/gathered/examples/imagenet.html in the training section. If you open "train_mnist_siamese.sh" you will find it has the same command as the tutorial I sent. You need to familiarize yourself first with caffe before experimenting.

**Comment by georgiazhang** [comment]
2.  I mean which algorithm you used to get the data.txt,i googled the "image_raw in a git ", still don't know how to deal with it.Can you explain it  in  detail?
    I am new to caffe, i will do as you said, thank you very much!

**Comment by nassarofficial** [comment]
What algorithm? I created the dataset myself. image_raw is the input u give to your model. I'm sorry but your questions are vague, and cant really explain to you how caffe works because there are much better online content that my explanation.
