### ISSUE TITLE
Meaning of train.txt and train2.txt

### ISSUE THREAD

**Issue by RaidenCJ** [nassarofficial/Siamese_network_caffe#4]
Hello,
Could you explain the train.txt and train2.txt?
What's the label 0 and 1 mean?Could I use different pictures in train.txt and train2.txt

**Comment by nassarofficial** [comment]
If you have 2 types of images or data inputs, each file (train.txt and train2.txt) corresponds to that. 0 and 1 are the labels for the images to say if each pair is similar or not.

For example:
Left Signature (train.txt)           |      Right Signature (train2.txt)
/path/data1/johndoe.jpg   1      |      /path/data2/johndoe.jpg   1 
/path/data1/mattdoe.jpg   1      |      /path/data2/mattdoe.jpg   1 
/path/data1/mattdoe.jpg   0     |       /path/data2/johndoe.jpg   0

**Comment by RaidenCJ** [comment]
@nassarofficial Great!
Thank you very much for your answser!
Could you share your deploy.prototxt also?

**Comment by RaidenCJ** [comment]
@nassarofficial
I already have deploy.prototxt now 
Could you help to explain how can I use it ?How to check 2 pictures if they are similar with new trained model with caffe? I mean I don't know how to make 2 images as input at one time

**Comment by sunny2Wang** [comment]
I have the same question with RaidenCJ, could you please tell us the usage? Thanks very much.

**Comment by RaidenCJ** [comment]
@sunny2Wang ,
I have uploaded a new siamese demo ,
https://github.com/RaidenCJ/Siamese_demo

Hope it can help!

**Comment by nassarofficial** [comment]
@sunny2Wang I'm sorry I really can't find the deploy.prototxt and I'm am really not working on the project anymore.
